# Generated by Django 4.2.18 on 2025-09-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.BigIntegerField(help_text='NHL API game ID', unique=True)),
                ('season', models.IntegerField(help_text='Season (e.g., 20252026)')),
                ('game_type', models.IntegerField(choices=[(1, 'Preseason'), (2, 'Regular Season'), (3, 'Playoffs')], help_text='Game type')),
                ('game_date', models.DateField(help_text='Game date')),
                ('home_team_id', models.IntegerField(help_text='Home team NHL API ID')),
                ('home_team_name', models.CharField(help_text='Home team name', max_length=100)),
                ('home_team_abbreviation', models.CharField(help_text='Home team abbreviation', max_length=5)),
                ('home_team_score', models.IntegerField(blank=True, help_text='Home team score', null=True)),
                ('home_team_sog', models.IntegerField(blank=True, help_text='Home team shots on goal', null=True)),
                ('home_team_record', models.CharField(blank=True, help_text='Home team record', max_length=20, null=True)),
                ('home_team_logo_url', models.URLField(blank=True, help_text='Home team logo URL', null=True)),
                ('away_team_id', models.IntegerField(help_text='Away team NHL API ID')),
                ('away_team_name', models.CharField(help_text='Away team name', max_length=100)),
                ('away_team_abbreviation', models.CharField(help_text='Away team abbreviation', max_length=5)),
                ('away_team_score', models.IntegerField(blank=True, help_text='Away team score', null=True)),
                ('away_team_sog', models.IntegerField(blank=True, help_text='Away team shots on goal', null=True)),
                ('away_team_record', models.CharField(blank=True, help_text='Away team record', max_length=20, null=True)),
                ('away_team_logo_url', models.URLField(blank=True, help_text='Away team logo URL', null=True)),
                ('venue_name', models.CharField(blank=True, help_text='Venue name', max_length=200, null=True)),
                ('start_time_utc', models.DateTimeField(help_text='Game start time in UTC')),
                ('eastern_utc_offset', models.CharField(blank=True, max_length=10, null=True)),
                ('venue_utc_offset', models.CharField(blank=True, max_length=10, null=True)),
                ('venue_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('game_state', models.CharField(choices=[('FUT', 'Future'), ('PRE', 'Pre-Game'), ('LIVE', 'Live'), ('CRIT', 'Critical'), ('FINAL', 'Final'), ('OFF', 'Official')], max_length=10)),
                ('game_schedule_state', models.CharField(default='OK', max_length=20)),
                ('neutral_site', models.BooleanField(default=False)),
                ('game_center_link', models.CharField(blank=True, max_length=200, null=True)),
                ('tickets_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-game_date', '-start_time_utc'],
                'indexes': [models.Index(fields=['game_date'], name='nhl_data_ga_game_da_021f2f_idx'), models.Index(fields=['game_state'], name='nhl_data_ga_game_st_5b6087_idx'), models.Index(fields=['season', 'game_type'], name='nhl_data_ga_season_56e99d_idx')],
            },
        ),
    ]
