# Generated by Django 5.2.6 on 2025-09-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_bot',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='language_code',
        ),
    ]
